### ISSUE TITLE
I can only upload Gcodes

### ISSUE THREAD

**Issue by Genosystem** [rlogiacco/UploadAnything#1]
I've this configuration:
3mf, obj, stl, png, gif, jpg, bin 
But only the gcodes are upload to Sdcard.
The rest of the files leave the progress bar in an eternal "Saving"
Thanks

**Comment by rlogiacco** [comment]
When you say "sdcard" do you mean the sd card on the printer? Because I didn't test that as my printer doesn't have an SD card, so I need more info to have an idea where the issue lies...

**Comment by Genosystem** [comment]
Yes, I'm talking about SDCard of the printer.
What info do you need?

**Comment by rlogiacco** [comment]
OK, so:

1. does it work as expected if you upload to the octoprint storage (upload locally)?
1. in settings > logging > octoprint.log do you see anything relevant to the plugin or the pending file transfer? (if so, please attach here)
1. do you have other plugins controlling file extensions installed?

**Comment by akamensky** [comment]
@rlogiacco I can test on my SKR Pro board. Not sure how upload is implemented in marlin (did not look at the code), but if it is implemented as byte copying, then it should just work.

**Comment by Noeljunior** [comment]
I have a similar setup as @Genosystem and same problem. I have a SKR pro which can only be updated with a firmware.bin file in the onboard sdcard and then a reboot. My accepted extensions are the same and I'm trying to upload a firmware.bin file.

1. The progress hangs at 100% if uploaded to printer's SD. I can upload to octoprint's storage though.
2. octoprint.log's last message is my login, no errors.
3. no other plugins that manage any kind of upload feature.

Anything else I can test for you?

**Comment by Noeljunior** [comment]
I just checked the onboard's sdcard on my computer and no file if there either. Is marlin not accepting some files?

**Comment by akamensky** [comment]
For SKR Pro board firmware upload MarlinBft plugin works well. There are some changes needed to enable some options in firmware to make it work. But otherwise it works rather well.

**Comment by Noeljunior** [comment]
#2 https://github.com/MarlinFirmware/Marlin/pull/14817

@akamensky, thanks. Notice that few minutes ago.

@rlogiacco, let me suggest, if possible, to cancel uploads to printer's sdcard that are not gcode. Or at least warn the user about this.

**Comment by rlogiacco** [comment]
This plugin is meant to allow to upload anything, I use it daily to upload STL files, both in ASCII and BINARY form.... I upload PNG and JPEG files as well.... so your suggestion actually defies the purpose of the plugin: the existing interface already blocks anything other than gcode.

**Comment by akamensky** [comment]
Well. To be fair plug-in is called Upload Anything. But it can't upload everything I throw at it. Which is confusing.

**Comment by rlogiacco** [comment]
😄 I guess you are welcome to contribute any fix... it works on my octopi and it seems to work on many others, but it's not easy to fix an issue if you just say "it's not working"....

I did successfully upload a .bin file on my setup... so... which version of octoprint are you running and which python version?
